[0m08:28:02.024514 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002B4C0410980>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002B4BE129E50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002B4C1457D90>]}


============================== 08:28:02.032851 | 3913b559-00e4-4ee9-92a1-49c1dab5060c ==============================
[0m08:28:02.032851 [info ] [MainThread]: Running with dbt=1.10.10
[0m08:28:02.033647 [debug] [MainThread]: running dbt with arguments {'partial_parse': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'send_anonymous_usage_stats': 'True', 'version_check': 'True', 'cache_selected_only': 'False', 'target_path': 'None', 'use_colors': 'True', 'invocation_command': 'dbt init', 'log_format': 'default', 'warn_error': 'None', 'introspect': 'True', 'debug': 'False', 'printer_width': '80', 'fail_fast': 'False', 'no_print': 'None', 'use_experimental_parser': 'False', 'log_cache_events': 'False', 'empty': 'None', 'quiet': 'False', 'indirect_selection': 'eager', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\andreas\\.dbt', 'static_parser': 'True', 'write_json': 'True'}
[0m08:28:10.996142 [debug] [MainThread]: Starter project path: C:\Users\andreas\Documents\AcadÃªmico\CURSOS\udemy\mlops\teste_dbt\venv\Lib\site-packages\dbt\include\starter_project
[0m08:28:11.017034 [info ] [MainThread]: 
Your new dbt project "projeto1" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m08:28:11.017637 [info ] [MainThread]: Setting up your profile.
[0m08:28:48.952551 [info ] [MainThread]: Profile projeto1 written to C:\Users\andreas\.dbt\profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m08:28:48.953627 [debug] [MainThread]: Command `dbt init` succeeded at 08:28:48.953516 after 47.11 seconds
[0m08:28:48.953941 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002B4C25A7360>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002B4C25AEC30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002B4C15199D0>]}
[0m08:28:48.954287 [debug] [MainThread]: Flushing usage events
[0m08:28:49.995028 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m22:58:35.724448 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000232B5D9C980>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000232B3AB9E50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000232B6DE3D90>]}


============================== 22:58:35.752246 | d8937875-9b05-48fc-9646-0aed0e5c0869 ==============================
[0m22:58:35.752246 [info ] [MainThread]: Running with dbt=1.10.10
[0m22:58:35.754247 [debug] [MainThread]: running dbt with arguments {'partial_parse': 'True', 'profiles_dir': 'C:\\Users\\andreas\\.dbt', 'send_anonymous_usage_stats': 'True', 'use_colors': 'True', 'cache_selected_only': 'False', 'target_path': 'None', 'warn_error': 'None', 'invocation_command': 'dbt seed --full-refresh', 'log_format': 'default', 'version_check': 'True', 'introspect': 'True', 'debug': 'False', 'printer_width': '80', 'fail_fast': 'False', 'no_print': 'None', 'empty': 'None', 'quiet': 'False', 'use_experimental_parser': 'False', 'log_cache_events': 'False', 'indirect_selection': 'eager', 'log_path': 'logs', 'write_json': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'static_parser': 'True'}
[0m22:58:35.756385 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\andreas\Documents\AcadÃªmico\CURSOS\udemy\mlops\teste_dbt\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m22:58:35.759305 [debug] [MainThread]: Command `dbt seed` failed at 22:58:35.758903 after 0.80 seconds
[0m22:58:35.760450 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000232B6F2B6F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000232B6EB28D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000232B6EA4AF0>]}
[0m22:58:35.761596 [debug] [MainThread]: Flushing usage events
[0m22:58:37.577954 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m22:58:53.864551 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001DB7A970980>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001DB78691E50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001DB7B9B3D90>]}


============================== 22:58:53.894470 | 9fc2bfbb-bf8a-4a17-b88b-317953862a86 ==============================
[0m22:58:53.894470 [info ] [MainThread]: Running with dbt=1.10.10
[0m22:58:53.896826 [debug] [MainThread]: running dbt with arguments {'partial_parse': 'True', 'profiles_dir': 'C:\\Users\\andreas\\.dbt', 'send_anonymous_usage_stats': 'True', 'use_colors': 'True', 'cache_selected_only': 'False', 'target_path': 'None', 'warn_error': 'None', 'invocation_command': 'dbt seed', 'log_format': 'default', 'version_check': 'True', 'introspect': 'True', 'debug': 'False', 'log_cache_events': 'False', 'fail_fast': 'False', 'no_print': 'None', 'quiet': 'False', 'use_experimental_parser': 'False', 'empty': 'None', 'printer_width': '80', 'log_path': 'logs', 'indirect_selection': 'eager', 'write_json': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'static_parser': 'True'}
[0m22:58:53.898576 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\andreas\Documents\AcadÃªmico\CURSOS\udemy\mlops\teste_dbt\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m22:58:53.902026 [debug] [MainThread]: Command `dbt seed` failed at 22:58:53.901588 after 0.43 seconds
[0m22:58:53.903297 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001DB7BAFB6F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001DB7BA868D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001DB7BA78AF0>]}
[0m22:58:53.904647 [debug] [MainThread]: Flushing usage events
[0m22:58:55.744446 [debug] [MainThread]: An error was encountered while trying to flush usage events
